<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.qiwumind</groupId>
    <artifactId>next-components</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <parent>
        <groupId>com.qiwumind</groupId>
        <artifactId>next-dependencies</artifactId>
        <version>${revision}</version>
        <relativePath>next-dependencies</relativePath>
    </parent>

    <properties>
        <revision>1.1.0.jdk21-SNAPSHOT</revision>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <timestamp>${maven.build.timestamp}</timestamp>
        <maven.build.timestamp.format>yyyy-MM-dd HH:mm:ss</maven.build.timestamp.format>
    </properties>
    <description>
        该包是技术组件，每个子包，代表一个组件。每个组件包括两部分：
        1. core 包：是该组件的核心封装
        2. config 包：是该组件基于 Spring 的配置

        技术组件，也分成两类：
        1. 框架组件：和我们熟悉的 MyBatis、Redis 等等的拓展
        2. 业务组件：和业务相关的组件的封装，例如说数据字典、操作日志等等。
        如果是业务组件，Maven 名字会包含 biz
    </description>
<!--    <distributionManagement>-->
<!--        <repository>-->
<!--            <id>nexus-release</id>-->
<!--            <name>nexus-release</name>-->
<!--            <url>http://10.0.0.2:8081/repository/maven-releases/</url>-->
<!--        </repository>-->
<!--        <snapshotRepository>-->
<!--            <id>nexus-snapshots</id>-->
<!--            <name>nexus-snapshots</name>-->
<!--            <url>http://10.0.0.2:8081/repository/maven-snapshots</url>-->
<!--        </snapshotRepository>-->
<!--    </distributionManagement>-->

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
            <!-- 统一 revision 版本 -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <version>${flatten-maven-plugin.version}</version>
                <configuration>
                    <flattenMode>oss</flattenMode>
                    <updatePomFile>true</updatePomFile>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>flatten</goal>
                        </goals>
                        <id>flatten</id>
                        <phase>process-resources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                        <id>flatten.clean</id>
                        <phase>clean</phase>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <pluginManagement>
            <plugins>
                <!-- maven-surefire-plugins 插件，用于运行单元测试。 -->
                <!-- 注意，需要使用 3.0.X+，因为要支持 Junit 5 版本 -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${maven-surefire-plugin.version}</version>
                    <configuration>
                        <argLine>-XX:+EnableDynamicAgentLoading</argLine>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven-compiler-plugin.version}</version>
                    <inherited>true</inherited>
                    <configuration>
                        <source>${java.version}</source>
                        <target>${java.version}</target>
                        <encoding>UTF-8</encoding>
                        <annotationProcessorPaths>
                            <path>
                                <groupId>org.springframework.boot</groupId>
                                <artifactId>spring-boot-configuration-processor</artifactId>
                                <version>${spring.boot.version}</version>
                            </path>
                            <path>
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok</artifactId>
                                <version>${lombok.version}</version>
                            </path>
                            <path>
                                <!-- 确保 Lombok 生成的 getter/setter 方法能被 MapStruct 正确识别，
                                     避免出现 No property named "xxx" exists 的编译错误 -->
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok-mapstruct-binding</artifactId>
                                <version>${lombok-mapstruct-binding.version}</version>
                            </path>
                            <path>
                                <groupId>org.mapstruct</groupId>
                                <artifactId>mapstruct-processor</artifactId>
                                <version>${mapstruct.version}</version>
                            </path>
                        </annotationProcessorPaths>
                        <!-- 编译参数写在 arg 内，解决 Spring Boot 3.2 的 Parameter Name Discovery 问题 -->
                        <debug>false</debug>
                        <compilerArgs>
                            <arg>-parameters</arg>
                        </compilerArgs>
                    </configuration>
                </plugin>
                <!-- ProGuard混淆插件 -->
                <plugin>
                    <groupId>com.github.wvengen</groupId>
                    <artifactId>proguard-maven-plugin</artifactId>
                    <version>${proguard-maven-plugin.version}</version>
                    <executions>
                        <!-- 配置执行阶段为package，即在打包时执行代码混淆 -->
                        <execution>
                            <phase>package</phase>
                            <goals>
                                <goal>proguard</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <!-- 指定输入Jar文件名 -->
                        <injar>${project.build.finalName}.jar</injar>
                        <!-- 指定输出Jar文件名，与输入Jar同名，实现覆盖 -->
                        <outjar>${project.build.finalName}.jar</outjar>
                        <!-- 混淆开关，默认为true -->
                        <obfuscate>true</obfuscate>
                        <!-- 指向proguard配置文件 -->
                        <proguardInclude>${project.basedir}/proguard.cfg</proguardInclude>
                        <attachArtifactClassifier>pg</attachArtifactClassifier>
                        <!-- 添加额外的jar包路径，通常为项目编译所需 依赖的JDK库（必须！否则无法识别Java原生类） -->
                        <libs>
                            <lib>${java.home}/lib/rt.jar</lib>
                            <lib>${java.home}/lib/jce.jar</lib>
                            <lib>${java.home}/lib/jsse.jar</lib>
                        </libs>
                        <!-- 过滤输入Jar中的文件，例如不处理META-INF目录下的文件 -->
                        <inLibsFilter>!META-INF/**,!META-INF/versions/9/**.class</inLibsFilter>
                        <!-- 指定输出目录 -->
                        <outputDirectory>${project.basedir}/target</outputDirectory>
                        <!-- 混淆配置的细节选项，例如指定哪些类不进行混淆，可选配置项 -->
                        <options>
                            <!-- 具体的混淆配置可在此处或外部配置文件中定义 -->
                        </options>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>


    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
            <comments>A business-friendly OSS license</comments>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>qiwumind</id>
            <name>qiwumind</name>
            <email>hc_kuisheng@126.com</email>
            <roles>
                <role>Developer</role>
            </roles>
        </developer>
    </developers>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-common</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-datasecure</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-oss</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-sequence</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-groovy</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-ons</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-rocketmq</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-feign-config</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-springboot-starter-groovy</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-springboot-starter-context</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-springboot-starter-banner</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-springboot-starter-sequence</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-springboot-starter-redis</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-springboot-starter-crypto</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-springboot-starter-file</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-springboot-starter-quartz</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-springboot-starter-starrocks</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-springboot-starter-compute</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-springboot-starter-cache</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-freemarker-generator</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-springboot-starter-pdf</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-springboot-starter-license</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-springboot-starter-wechat</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-springboot-starter-pricing</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-springboot-starter-hologres</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-springboot-starter-mybatis</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-springboot-starter-web</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-springboot-starter-security</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-springboot-starter-monitor</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-springboot-starter-protection</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-springboot-starter-job</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-springboot-starter-mq</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-springboot-starter-excel</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-springboot-starter-biz-tenant</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-springboot-starter-biz-data-permission</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.qiwumind</groupId>
                <artifactId>next-springboot-starter-biz-ip</artifactId>
                <version>${revision}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>


        <modules>
            <module>next-dependencies</module>
            <module>next-common</module>
            <module>next-datasecure</module>
            <module>next-oss</module>
            <module>next-sequence</module>
            <module>next-groovy</module>
            <module>next-ons</module>
            <module>next-rocketmq</module>
            <module>next-feign-config</module>
            <module>next-springboot-starter-groovy</module>
            <module>next-springboot-starter-context</module>
            <module>next-springboot-starter-banner</module>
            <module>next-springboot-starter-sequence</module>
            <module>next-springboot-starter-redis</module>
            <module>next-springboot-starter-crypto</module>
            <module>next-springboot-starter-file</module>
            <module>next-springboot-starter-quartz</module>
            <module>next-springboot-starter-starrocks</module>
            <module>next-springboot-starter-compute</module>
            <module>next-springboot-starter-cache</module>
            <module>next-freemarker-generator</module>
            <module>next-springboot-starter-pdf</module>
            <module>next-springboot-starter-license</module>
            <module>next-springboot-starter-wechat</module>
            <module>next-springboot-starter-pricing</module>
            <module>next-springboot-starter-hologres</module>
            <module>next-springboot-starter-mybatis</module>
            <module>next-springboot-starter-web</module>
            <module>next-springboot-starter-security</module>
            <module>next-springboot-starter-monitor</module>
            <module>next-springboot-starter-protection</module>
            <module>next-springboot-starter-job</module>
            <module>next-springboot-starter-mq</module>
            <module>next-springboot-starter-excel</module>
            <module>next-springboot-starter-biz-tenant</module>
            <module>next-springboot-starter-biz-data-permission</module>
            <module>next-springboot-starter-biz-ip</module>
        </modules>
</project>
